sih_analytics: # Este é o nome do perfil, que corresponde ao nome do seu projeto
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost # ou o host do seu DB
      user: postgres # seu usuário do postgres
      password: 1234 # sua senha do postgres
      port: 5432
      dbname: sih_rs
      schema: dbt_isadora # O dbt cria um schema para trabalhar
      threads: 1
